{{ if .Values.components.hdfs }}
apiVersion: v1
kind: Service
metadata:
  name: hdfs-nfs
  labels:
    component: hdfs-nn
spec:
  type: ClusterIP
  clusterIP: {{ .Values.hdfs.nfsIP }}
  ports:
    - name: portmapper
      port: 111
      protocol: TCP
    - name: nfs
      port: 2049
      protocol: TCP
    - name: mountd
      port: 4242
      protocol: TCP
  selector:
    component: hdfs-nn 
---
{{ end }}
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: hdfs
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: hdfs
spec:
  storageClassName: hdfs
  capacity:
    storage: 3000Gi
  accessModes:
    - ReadWriteMany
{{ if eq .Values.kubernetesType "minikube" }}              
  hostPath: 
    path: /data/scale-nfs
    type: DirectoryOrCreate
{{ else }}
  mountOptions:
    - vers=3
    - proto=tcp
    - noacl
    - noatime
    - nolock
    - sync    
  nfs:
    server: {{ .Values.hdfs.nfsIP }}
    path: "/"
{{ end }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: hdfs
spec:
  storageClassName: hdfs
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 3000Gi

