{{ if .Values.components.git }}
apiVersion: v1
kind: Service
metadata:
  name: git
  labels:
    component: git
spec:
  type: ClusterIP
  ports:
  - port: 22
    name: ssh
  selector:
    component: git
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: git
spec:
  podManagementPolicy: Parallel
  serviceName: git
  selector:
    matchLabels:
      component: git  
  replicas: 1
  template:
    metadata:
      labels:
        component: git
    spec:
      terminationGracePeriodSeconds: 0
      tolerations:
        - key: scale
          operator: Exists
          effect: NoSchedule      
{{ if .Values.nodeGroupLabel }}
      nodeSelector:
        {{ .Values.nodeGroupLabel }}: core
{{ end }}      
      imagePullSecrets:
      - name: {{ .Values.registry.secret.name }}
      containers:
      - name: scale-git
        image: {{ .Values.registry.repository }}/{{ .Values.imageGit }}:{{ .Values.imageTag }}
        imagePullPolicy: {{ .Values.imagePullPolicy }}
{{ if .Values.defineResources }}        
        resources:
          requests:
            memory: "256Mi"
            cpu: "200m"
{{ end }}            
{{ end }}