{{ if .Values.components.logging }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: apm-server-config
  labels:
    component: apm-server
data:
  apm-server.yml: |-
    apm-server:
      host: "0.0.0.0:8200"
      frontend:
        enabled: false
    setup.template.settings:
      index:
        number_of_shards: 1
        codec: best_compression
    setup.kibana:
      host: "kibana-logging"
    output.elasticsearch:
      hosts: ["elasticsearch-logging"]
      indices:
        - index: "apm-7.5.1-sourcemap"
          when.contains:
            processor.event: "sourcemap"
        - index: "apm-7.5.1-error-%{+yyyy.MM.dd}"
          when.contains:
            processor.event: "error"
        - index: "apm-7.5.1-transaction-%{+yyyy.MM.dd}"
          when.contains:
            processor.event: "transaction"
        - index: "apm-7.5.1-span-%{+yyyy.MM.dd}"
          when.contains:
            processor.event: "span"
---
apiVersion: v1
kind: Service
metadata:
  name: apm-server
  labels:
    component: apm-server
spec:
  ports:
  - port: 8200
    targetPort: 8200
    name: http
    nodePort: 31000
  selector:
    component: apm-server
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: apm-server
spec:
  replicas: 1
  selector:
    matchLabels:
      component: apm-server
  template:
    metadata:
      labels:
        component: apm-server
    spec:
      tolerations:
        - key: scale
          operator: Exists
          effect: NoSchedule      
{{ if .Values.nodeGroupLabel }}
      nodeSelector:
        {{ .Values.nodeGroupLabel }}: logging
{{ end }}
{{ if .Values.registry.publicImagesSecretNeeded }}
      imagePullSecrets:
      - name: {{ .Values.registry.secret.name }}
{{ end }}          
      containers:
      - name: apm-server
        image: {{ .Values.apm.image.registry }}/{{ .Values.apm.image.repository }}:{{ .Values.apm.image.version }}
        ports:
        - containerPort: 8200
          name: apm-port
        volumeMounts:
        - name: apm-server-config
          mountPath: /usr/share/apm-server/apm-server.yml
          readOnly: true
          subPath: apm-server.yml
      volumes:
      - name: apm-server-config
        configMap:
          name: apm-server-config
{{ end }}