kind: Deployment
apiVersion: apps/v1
metadata:
  name: my-release-keycloak
  namespace: default
  labels:
    app: keycloak
    release: my-release
spec:
  replicas: 1
  selector:
    matchLabels:
      app: keycloak
      release: my-release
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: keycloak
        release: my-release
    spec:
      tolerations: 
        - key: "vtd-scale-9"
          operator: "Exists"
          effect: "NoSchedule"
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: my-release-keycloak
      containers:
        - name: keycloak
          image: jboss/keycloak
          imagePullPolicy: Never
          env:
            - name: KEYCLOAK_USER
              value: admin
            - name: KEYCLOAK_PASSWORD
              value: admin
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          volumeMounts:
            - name: data
              mountPath: /opt/jboss/keycloak/standalone/data
---             
kind: Service
apiVersion: v1
metadata:
  name: my-release-keycloak
  namespace: default
spec:
  ports:
    - name: http
      protocol: TCP
      port: 30040
      targetPort: 8080
      nodePort: 30080
  selector:
    app: keycloak
    release: my-release
  type: LoadBalancer
---
kind: Ingress
apiVersion: extensions/v1beta1
metadata:
  name: my-release-keycloak
  namespace: default
  labels:
    app: keycloak
    release: my-release
spec:
  rules:
    - host: keycloak.local.scale-hexagon.com
      http:
        paths:
          - path: /
            backend:
              serviceName: my-release-keycloak
              servicePort: http
