kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: my-release-keycloak
  namespace: default
  labels:
    app: keycloak
    release: my-release
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: csi-rbd-sc
  resources:
    requests:
      storage: 8Gi
