{{ if .Values.components.logging }}
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: elasticsearch-curator
  labels:
    k8s-app: elasticsearch-logging
spec:
  schedule: "0 0 * * *"
  jobTemplate:
    spec:
      template:
        metadata:
          name: elasticsearch-curator
          labels:
            k8s-app: elasticsearch-logging
        spec:
          restartPolicy: "Never"
          tolerations:
            - key: scale
              operator: Exists
              effect: NoSchedule      
{{ if .Values.nodeGroupLabel }}
          nodeSelector:
            {{ .Values.nodeGroupLabel }}: logging
{{ end }}
{{ if .Values.registry.publicImagesSecretNeeded }}
          imagePullSecrets:
          - name: {{ .Values.registry.secret.name }}                     
{{ end }}
          containers:
          - name: ingestor
            image: {{ .Values.curator.image.registry }}/{{ .Values.curator.image.repository }}:{{ .Values.curator.image.version }}
            args: ["sh", "-c", "pip install elasticsearch-curator && curator_cli --host elasticsearch-logging delete_indices --filter_list '[{\"filtertype\":\"age\",\"source\":\"creation_date\",\"direction\":\"older\",\"unit\":\"days\",\"unit_count\":7},{\"filtertype\":\"pattern\",\"kind\":\"prefix\",\"value\":\"logstash\"}]' || true"]
      backoffLimit: 1
{{ end }}
